-- Question 1
-- The youngest pet is Anna. (birthday is 2024-10-12)
    -- Commands:
        -- SELECT *
        -- FROM pet
        -- ORDER BY dateOfBirth DESC
        -- LIMIT 1
-- Question 2
-- Yes, you would just have to query the records that contains a conditional
-- that would have filter out any birthdays that happened 3-4 years ago
--  (there should be 2 records)
    -- Commands:
        -- SELECT uuid
        -- FROM pet
        -- WHERE dateOfBirth > '2019-08-20' AND dateOfBirth < '2024-10-12'
-- Question 3
-- 
-- Question 4
--
-- Question 5
-- 
-- Question 6
--
-- Question 7
--
-- Question 8 (first version)
--
-- Question 8 (second version)
--